# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch: # this is the manual running of the workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  armDeploy: # the first job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subsciptionId: 155aacbd-0fdd-4a0f-97b0-7d2e2eb81010
          region: eastus
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions

